name: user_repository
description: "This Repository handles the user repo."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  rxdart: ^0.28.0
  path: ^1.9.1
  firebase_storage: ^13.0.2
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  